### ISSUE TITLE
[202002] 本月开源推荐

### ISSUE THREAD

**Issue by esmadrider** [ningowood/open-source-magazine#3]
在 2020-02 月期间，如果有任何推荐的资源，欢迎推荐在本 issues 下，也就不用开启过多新的 issue 了。模板不限，更欢迎你对资源的翻译、笔记和读后感！

以下内容均已收录，更多内容详见本月刊 [《开源爱好者月刊：第 2 期（202002）》](https://github.com/ningowood/open-source-magazine/blob/master/docs/ningowood-002.md)

**Comment by esmadrider** [comment]
#### [我们分析了GitHub上5.46 亿条日志，发现中国开源虽然贡献大但还有这些不足...](https://github.com/X-lab2017/github-analysis-report-2019/blob/master/REPORT.md)

![](https://user-images.githubusercontent.com/19285461/73604735-824fbf80-45d0-11ea-90a2-7c4f0330a347.png)

* 时间：2020-02-02
* 作者：infoQ 和 X-lab 开放实验室
* 类别：资讯

本文通过大量客观数据的罗列，肯定了中国开源对世界的贡献，但也指出了很多不足之处。

本文分析的角度如下，并附上一些重点感悟。

* 宏观统计结果：大多数项目处于低活跃、参与人数少的状态。活跃度高和参与人数多的项目的占比都是万分之一级别的。
* 世界 Top 10 开发者账号：都是机器人，侧面反映出开源自动化流程的强大。
* 世界 Top 10 项目：大公司以及民间主动发起的项目都有，涵盖前端、容器编排、深度学习以及文档整理等多个领域。
* 中国 Top 20 项目分析：涵盖前端（几乎占据榜单一半，但缺少核心项目）、后端、教育、求职、人文关怀等诸多领域。
* Repo 协作关系：我们可以使用工具来分析 Commit 生成协作图。
* 开发语言分析：活跃度上，JS 第一（无需编译，浏览器直接运行），Py 第二（高可读性，应用范围逛，人工智能优先语言），TS 第三（同属于 JS 生态圈）等，相继的是 Java、C++、Go......。
* 国内技术公司开源项目一览：阿里领衔，各大企业近年来均在不断加大开源社区生态建设。
* 展望：Github 一定程度上受美国法律制约，中国也需要自己的核心技术。

边读边好奇（有机会回答这些问题）：

* Github 机器人怎么玩？开源自动化流程有哪些，以及相应的解决方案在哪？
* Repo 协作关系是怎么画出来的？-> 答案：[Git2Net](https://github.com/gotec/git2net)

文章附录粘贴在这里慢慢读：

* [分析程序和原文地址](https://github.com/X-lab2017/github-analysis-report-2019)
* [GitHub 官方 2019 年度报，](https://octoverse.github.com)
* [中国开源年度报告](https://kaiyuanshe.cn/project/china-open-source-report)
* [中国开源项目 Grank 分析报告（2019）]( https://linux.cn/article-11755-1.html)
* [徐川，覃云：中国互联网公司开源项目调研报告](https://www.infoq.cn/article/G4O6JUhJF*Tsv9eWM0L6)
* 云计算开源产业联盟，开源产业白皮书（2019），2019 云计算开源产业大会, 北京.
* [Gitee 2019 年度数据报告]( https://oschina.gitee.io/gitee-2019-annual-report/?utm_source=giteeblog)

**Comment by yangdajiang** [comment]
#### [2020年会为开发人员带来什么，以及更多的行业趋势](https://opensource.com/article/20/1/hybrid-developer-future-industry-trends?utm_campaign=intrel)

![](https://user-images.githubusercontent.com/22792728/74098541-614d1880-4b54-11ea-9574-5d463f22f2d1.png)

- 时间：2020-01-25
- 作者： Tim Hildred (Red Hat)
- 类别：资讯

文章对2020年开发人员流行的开发方式及主流设计思想进行简单介绍。

本文分析角度及重点感悟。

- 开发者在2020年工作方式将会向着越来越“分布式”的方向发展，自动化的代码分布将会变得更好（甚至于无处不在），开发者的工具将会变得更“智能”，无服务器计算方式也会快速发展。
- “无代码”开发的发展有喜有忧；“无代码”工具已有一定程度发展，更加简单的抽象和语法，让开发人员摆脱了一定代码的束缚，但过度“隐藏”了底层的代码的工具，将会在解决需求的能力上大打折扣。
- 万物Java，Java诞生25周年，技术中快速发展的事物是可以丢弃的事物。当您知道要保留很长时间时，可能会在构建对象时对优先级做出不同的选择。一次性的和长寿的都有它们的位置，并且Java社区多年来做出了足够好的决定，使得语言本身可以在这两个阵营中站稳脚跟。

文章附录

- [开发人员在2020年的工作方式](https://thenextweb.com/readme/2020/01/15/how-developers-will-work-in-2020/)
- [2020年预测：Cloud-y，有机会混合使用](https://www.itproportal.com/features/2020-forecast-cloud-y-with-a-chance-of-hybrid/)
- [”无代码”妄想](https://www.alexhudson.com/2020/01/13/the-no-code-delusion/)
- [万物Java](https://appdevelopermagazine.com/all-things-java/)

**Comment by esmadrider** [comment]
#### [2019-2020 中国开发者调查报告完整版](https://download.csdn.net/download/xhwuli/12195346)

![](https://user-images.githubusercontent.com/19285461/75431180-6c42de00-5987-11ea-91ab-a33dc46e11c3.png)

* 时间：2020-02-27
* 作者：CSDN
* 类别：资源
* 相关文章：[两成开发者月薪超 1.7 万、算法工程师最紧缺！ | 中国开发者年度报告](https://mp.weixin.qq.com/s/6FaOYoIEtxjWN-265ppKHg)

CSDN 通过平台优势，进行大数据分析和一定的问卷调查后推出。

### 资源目录简介

**1. 报告概述**

使用了良好的调查方法和数据分析工具，邀请了业界各细分领域专家，有华为云的特别支持。

**2. 重要发现**

* 三十岁以下开发者占比超 8 成，近半数开发者在一线城市；
* 开发者学习热情高涨，5 成开发者通过自学，31% 接受了软件开发的在职培训；
* 6 成开发者在使用 Java 语言，近 5 成开发者近期最想学 Python 语言；
* 大数据技术应用开始普及，但大数据应用场景逐渐多元化；
* 区块链技术近两年是热点，23% 开发者有应用或准备应用，72% 开发者尚处于初步了解阶段， 4% 开发者完全不了解；
* 人工智能技术日益受到企业和市场的关注，应用前景广阔但任重道远；
* 物联网产业链上企业最多的在智能设备环节，大数据分析是物联网最大的应用领域；
* Apache 项目和 Linux 是开发者较为喜欢的开源项目。

其中，关于开源：

* Apache 项目和 Linux 是开发者较为喜欢的开源项目；
* 半数开发者很少参与开源项目的开发、维护、运营和社区发展等；全职参与的仅7%
* 超过6成开发者未从开源项目获取收入；
* 77% 开发者每周在开源上投入不超过 5 小时。

**3. 开发者现状分析**

* 年龄分布 (~30):(30~40):(40~) 约等于 80:18:2
* 8.5成开发者月薪在5千至3万元之间，19.6%开发者月薪超过1.7万元
* 开发者从业年限集中在 5 年以内
* 工作时间自由的人群中，收入超过 1.7 万的比重最高
* 自学是开发者持续学习的主要路径（7% 是从开源软件方面的贡献中持续学习）
* 37%开发者或其公司愿意付费学习
* 59%开发者每周学习6小时以上
* 70%的开发者参加培训的预算来自个人
* Java 长盛：使用最多，最想学
* 7 成以上开发者在使用 Windows 操作系统，83% 的开发者在使用 MySQL 数据库
* Node.js 是相对使用普遍的技术框架
* Visual Studio 是最为普遍使用的开发环境
* 34% 的开发者用容器进行开发
* Arm 架构具备多核分布式优势是开发者选择 Arm 架构的普遍原因
* 41% 开发者认为当下自主可控硬件及软件生态的主要问题是缺乏开源社区的足够支持，许 多软件基础设施缺乏适配

**4. 大数据技术应用现状分析**

* 有 81% 的企业在运用大数据技术进行应用开发
* 私有云部署解决方案是企业构建大数据平台的主要方式
* 78% 企业大数据团队规模在 30 人以下
* 64% 的开发者表示应用大数据实现了更智能的决策
* 大数据技术应用场景逐渐多元化，以数据分析及可视化最为普遍
* 日志数据是企业大数据平台处理的主要数据类型
* 超 7 成的企业日均处理数据规模在 10TB 以下
* 55% 企业大数据平台的集群规模在 20 个节点以上
* 仅 19% 企业使用商业发行版 Hadoop 版本搭建数据平台
* Spark 是企业大数据平台最普遍的组件
* Redis 和 Kafka 是最普遍使用的消息队列和数据采集技术组件

**5. 区块链技术应用现状分析**

* 22% 的开发者正在用或者准备用区块链技术解决技术问题
* 43% 的受访者在从事公有链（比特币、以太坊等）的开发
* 比特币和以太坊是当前两种主流的区块链开发平台
* 区块链应用方向前几名有金融、智能硬件及物联网、传统行业解决方案、游戏等

**6. 人工智能技术应用现状分析**

* 64% 的企业尚未实现智能化
* 5 成公司算法工程师团队规模小于 10 人
* 机器学习/深度学习算法工程师最急缺
* TensorFlow 是人工智能领域主流深度学习框架
* 制造、金融行业是 AI 技术结合最多的行业
* 35% 开发者选用国产 AI 芯片应用于自己的 AI 开发，最看重对主流 AI 框架的支持能力

**7. 物联网技术应用现状分析**

* 69% 的开发者认为未来 5G 网络的传输速率能达到 4G 网络的 10 倍以上
* 物联网产业链上企业最多的在大数据分析环节
* 智能网联汽车是受到 5G 影响较大的领域 
* 近7成开发者公司认为应该降低数据流量的套餐费用，87%的开发者认为5G费用过高
* 影响 5G 普及的三大因素有 5G 价格未定、运营商的开发程度、需要更换手机
* Linux 和 Windows 是较普遍的操作系统
* 阿里物联和华为云是应用相对普遍的工业 IoT 云平台
* Wi-Fi 是应用最普遍的物联网通信技术

**8. 开源技术应用现状分析**

* 68% 的开发者接触开源的时间在 2-5 年
* 42% 的开发者首次接触的开源产品是开发工具及框架
* 77% 开发者每周在开源上投入时间不超过 5 小时
* 65% 开发者不曾在开源上获得收入
* 53% 开发者很少参与开源项目
* 开发者最喜欢的开源项目是 Apache

**文章中推荐的其它资源**

* [Inside the Machine](http://joe90.yolasite.com/resources/InsidetheMachine.pdf)：介绍 CPU 和计算机体系结构的电子书，需翻墙
* [xv6](https://pdos.csail.mit.edu/6.828/2012/xv6.html)：MIT等大学教学用操作系统，从零开始构建操作系统
* [udemy.com](https://www.udemy.com/)：(收费) 仅 10 美元的海量视频课程
* [coursera.org](https://www.coursera.org/)：(部分免费) 全世界顶级大学提供的网络课程
* [classcentral.com](http://classcentral.com/)： 在线课程搜索网站

### 简单的感悟与思考

* 开发者年龄偏向年轻、薪资偏向高薪，数据背后都与每个开发者生活息息相关
* 34% 的开发者用容器进行开发，现在不了解容器将会很被动
* 终身学习是现代人保持竞争力甚至是维持生存的必要手段。如果想要在职业道路上有更进一步的发展，除了需要有专业技术，还需要广泛的元技能、跨学科知识，例如管理学、经济学、社会学知识等等，而这些技能和 知识必须是通过长时间的学习和积累才能获得的
* 编程语言使用人数前三名：Java、JavaScript、SQL，其中 SQL 不容小视前后端必备（用来数据处理，配合 MySQL 学习，Elasticsearch 可选）
* Node.js 是最多被用到的框架，这和当今多端开发的趋势密不可分
* 主流的 Web 部署方案：后端微服务，中间 Node.js 粘合处多端的 APIs
* 微软投入了大量的研发力量，Windows 平台不容小视
* 以家庭为细胞的相关局域网与物联网值得每一个开源开发者学习：开源的动力一定是从开源开发者自身需求出发，而家庭是开源开发者的出生地
* 物联网 +：以手机为代表的个人计算中心和以家庭网关、城市大脑为代表的边缘计算中心进行智能决 策，从而更加便利人们的生活
* 现如今，每个开发者都离不开开源项目，每个开发者也得通过大量时间去持续学习，如何呼吁让更多开发者从开源中学习并回馈开源，行业又该如何帮助开发者们理解开源、建设开源，都是接下来面对的重点。

**Comment by esmadrider** [comment]
#### [Scalar：提升操作巨型 Git 仓库速度](https://github.com/microsoft/scalar)

* 作者：微软
* 类别：开源项目

![](https://user-images.githubusercontent.com/19285461/75442136-c351ae80-5999-11ea-8347-3405771fb773.png)

Git 作为版本控制系统的优势很明显，但当 Git 仓库的历史记录过多、跟踪的代码变动过为庞大时，Git 变得难以管理所有数据，导致其运行越来越不顺畅。使用 Git 开发庞大的 Windows 操作系统的微软显得颇有经验：早期使用虚拟文件系统开发 VFS for Git（简称 GVFS），回馈改进了 Git 客户端本身，现在开源了一个无需虚拟文件系统即可支持巨型 Git 仓库的项目，Scalar。

Scalar 是一个使用 C# 编写的 .NET Core 应用程序，通过设置所建议的配置值和运行后台维护来最大程度优化 Git 命令的性能。无论开发者使用什么服务来托管代码仓库，Scalar 都能有效地加速Git 指令。

**Comment by esmadrider** [comment]
#### [免费开源的 Playnite 被他人发布在 Steam 上，售价 100 美元](https://www.pcgamer.com/someone-is-selling-the-free-open-source-playnite-launcher-on-steam-for-dollar100)

![](https://user-images.githubusercontent.com/19285461/75442996-7d95e580-599b-11ea-8964-989cca32c718.png)

* 发布时间：2020-02-18
* 作者：JosefNemec
* 类别：一句话消息

Playnite 是一个一站式游戏启动器，支持多种第三方游戏库，如 Steam、GOG、Origin、Battle.net 和 Uplay。包括游戏仿真支持，为玩家的游戏提供一个统一的界面。Playnite 使用 C# 开发，目前只能在 Windows 中运行。

近日，有其他用户将以 MIT 协议免费开源的 Playnite 发送至 Steam 上售卖 100 美元（国区 256 人民币），然而这并不侵权。

**Comment by esmadrider** [comment]
> #### [2020年会为开发人员带来什么，以及更多的行业趋势](https://opensource.com/article/20/1/hybrid-developer-future-industry-trends?utm_campaign=intrel)
> ![](https://user-images.githubusercontent.com/22792728/74098541-614d1880-4b54-11ea-9574-5d463f22f2d1.png)
> 
> * 时间：2020-02-09
> * 作者： Tim Hildred (Red Hat)
> * 类别：资讯
> 
> 文章对2020年开发人员流行的开发方式及主流设计思想进行简单介绍。
> 
> 本文分析角度及重点感悟。
> 
> * 开发者在2020年工作方式将会向着越来越“分布式”的方向发展，自动化的代码分布将会变得更好（甚至于无处不在），开发者的工具将会变得更“智能”，无服务器计算方式也会快速发展。
> * “无代码”开发的发展有喜有忧；“无代码”工具已有一定程度发展，更加简单的抽象和语法，让开发人员摆脱了一定代码的束缚，但过度“隐藏”了底层的代码的工具，将会在解决需求的能力上大打折扣。
> * 万物Java，Java诞生25周年，技术中快速发展的事物是可以丢弃的事物。当您知道要保留很长时间时，可能会在构建对象时对优先级做出不同的选择。一次性的和长寿的都有它们的位置，并且Java社区多年来做出了足够好的决定，使得语言本身可以在这两个阵营中站稳脚跟。
> 
> 文章附录
> 
> * [开发人员在2020年的工作方式](https://thenextweb.com/readme/2020/01/15/how-developers-will-work-in-2020/)
> * [2020年预测：Cloud-y，有机会混合使用](https://www.itproportal.com/features/2020-forecast-cloud-y-with-a-chance-of-hybrid/)
> * [”无代码”妄想](https://www.alexhudson.com/2020/01/13/the-no-code-delusion/)
> * [万物Java](https://appdevelopermagazine.com/all-things-java/)

感谢~ 但发现虽然你是 02-09 日推荐的这篇文章，而文章本身是 01-25 发布的，以后我们可以优先选择本月的文章这样更有本月的时效性感觉 :)

**Comment by esmadrider** [comment]
#### [pytorch3d：将 PyTorch 用于3D深度学习的函数库](https://github.com/facebookresearch/pytorch3d)

![](https://raw.githubusercontent.com/facebookresearch/pytorch3d/master/.github/pytorch3dlogo.png)

* 作者：Facebook
* 类别：开源项目

Facebook 近日开源了将 PyTorch 用于 3D 深度学习的函数库 PyTorch3D。Facebook 将这些功能打包成工具包，并提供了运算符、异构批处理功能和模块化可微分的渲染API等，帮助研究人员进行复杂的 3D 神经网络应用研究。
