### ISSUE TITLE
2020年会为开发人员带来什么，以及更多的行业趋势

### ISSUE THREAD

**Issue by yangdajiang** [ningowood/open-source-magazine#5]
[2020年会为开发人员带来什么，以及更多的行业趋势](https://opensource.com/article/20/1/hybrid-developer-future-industry-trends?utm_campaign=intrel)
![](https://user-images.githubusercontent.com/22792728/74098541-614d1880-4b54-11ea-9574-5d463f22f2d1.png)

- 时间：2020-02-09
- 作者： Tim Hildred (Red Hat)
- 类别：资讯

文章对2020年开发人员流行的开发方式及主流设计思想进行简单介绍。

本文分析角度及重点感悟。

- 开发者在2020年工作方式将会向着越来越“分布式”的方向发展，自动化的代码分布将会变得更好（甚至于无处不在），开发者的工具将会变得更“智能”，无服务器计算方式也会快速发展。
- “无代码”开发的发展有喜有忧；“无代码”工具已有一定程度发展，更加简单的抽象和语法，让开发人员摆脱了一定代码的束缚，但过度“隐藏”了底层的代码的工具，将会在解决需求的能力上大打折扣。
- 万物Java，Java诞生25周年，技术中快速发展的事物是可以丢弃的事物。当您知道要保留很长时间时，可能会在构建对象时对优先级做出不同的选择。一次性的和长寿的都有它们的位置，并且Java社区多年来做出了足够好的决定，使得语言本身可以在这两个阵营中站稳脚跟。

文章附录

- [开发人员在2020年的工作方式](https://thenextweb.com/readme/2020/01/15/how-developers-will-work-in-2020/)
- [2020年预测：Cloud-y，有机会混合使用](https://www.itproportal.com/features/2020-forecast-cloud-y-with-a-chance-of-hybrid/)
- [”无代码”妄想](https://www.alexhudson.com/2020/01/13/the-no-code-delusion/)
- [万物Java](https://appdevelopermagazine.com/all-things-java/)

**Comment by esmadrider** [comment]
很棒，感觉可以正式收录进去 2 月份月刊。

我们可以直接在 #3 里交流本月的新闻~ 这样就不用新开 issues 了 :)
